### ISSUE TITLE
The "sys" module is now called "util". It should have a similar interface.

### ISSUE THREAD

**Issue by mew7wo** [node-modules/weibo#13]
在NAE上使用A simple web with oauth login.，产生这个错误。

The "sys" module is now called "util". It should have a similar interface.
TypeError: Object #<Object> has no method 'oauth'
    at Object.<anonymous> (/home/admin/cnae/git/cnode-app-engine/apps/datamine/server.js:17:11)
    at [object Object]._compileFile (/home/admin/cnae/git/cnode-app-engine/lib/sandbox.js:347:49)
    at Object..js (/home/admin/cnae/git/cnode-app-engine/lib/sandbox.js:391:9)
    at [object Object].load (/home/admin/cnae/git/cnode-app-engine/lib/sandbox.js:150:17)
    at Function._loadFile (/home/admin/cnae/git/cnode-app-engine/lib/sandbox.js:176:10)
    at Function.run (/home/admin/cnae/git/cnode-app-engine/lib/sandbox.js:357:18)
    at Array.0 (/home/admin/cnae/git/cnode-app-engine/lib/child.js:83:11)
    at EventEmitter._tickCallback (node.js:192:40)

**Comment by fengmk2** [comment]
fixed in 0.6.1
