### ISSUE TITLE
500 VerifyCredentialsError: check sign error

### ISSUE THREAD

**Issue by leizongmin** [node-modules/weibo#44]
使用中间件来进行授权时，在QQ授权页面中登录并跳转回 `/oauth//callback` 时出错：

（使用新浪微博没问题，只在使用QQ时除了第一次成功外，后来每次都是出错）

```
Express
500 VerifyCredentialsError: check sign error
at TQQAPI.detect_error (x:\node_modules\weibo\lib\tqq.js:118:11)
at x:\node_modules\weibo\lib\tbase.js:306:16
at done (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:228:5)
at x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:399:9
at decodeContent (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:276:14)
at IncomingMessage. (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:377:7)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)
```

**Comment by fengmk2** [comment]
## 日久失修好久了, 求维护

@fengmk2
@Python发烧友
http://fengmk2.github.com
Sent with Airmail

On April 4, 2014 at 9:01:07 PM, 雷宗民 (notifications@github.com) wrote:

使用中间件来进行授权时，在QQ授权页面中登录并跳转回 /oauth//callback 时出错：

（使用新浪微博没问题，只在使用QQ时除了第一次成功外，后来每次都是出错）

Express
500 VerifyCredentialsError: check sign error
at TQQAPI.detect_error (x:\node_modules\weibo\lib\tqq.js:118:11)
at x:\node_modules\weibo\lib\tbase.js:306:16
at done (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:228:5)
at x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:399:9
at decodeContent (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:276:14)
at IncomingMessage. (x:\node_modules\weibo\node_modules\urllib\lib\urllib.js:377:7)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)

**Comment by leizongmin** [comment]
腾讯微博API文档对`check sign error`的描述：
http://wiki.open.t.qq.com/index.php/%E6%8A%80%E6%9C%AF%E7%B1%BBFAQ#.E8.AF.B7.E6.B1.82API.E8.BF.94.E5.9B.9Echeck_sign_error.E9.94.99.E8.AF.AF

> 此问题的原因主要是请求时生成的oauth_signature签名不对，后台在对请求鉴权时验证签名错误。
> 解决方法：检查你的生成的签名是否按照OAuth协议算法得出的签名，检查你的参数是否是UTF8，检查你的参数是否urlencode (urlencode 采用[RFC 3986标准])，或重复urlencode

**Comment by leizongmin** [comment]
不知道是不是腾讯微博API抽风了，明天再看看会不会自动变好。

**Comment by leizongmin** [comment]
经过几次测试，情况如下：
- 授权完成后首先调用 `/cgi-bin/access_token` 时没有问题，再调用 `/api/user/info` 获取用户信息时报错：`check sign error`
- 第一次授权能成功，退出登录后再授权就出错，隔几个小时之后（oauth_token改变了）再授权第一次又能成功
- 两次调用 `/api/user/info` 时的参数，除 `oauth_timestamp` 之外，其他都是一样的
- 初步判断是腾讯微博API的Bug

**Comment by fengmk2** [comment]
呃。。。。还有这种事情。。。
2014-4-8 下午12:32于 "雷宗民" notifications@github.com写道：
